# Basic arrays

In [1]:
import array as arr

In [14]:
arr1 = arr.array('i',
    [25,6,9,5,8]
)

In [2]:
import numpy as np

In [21]:
arr2 = np.array([5,8,9,6,5,4.8,7,5,6])
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 7. , 5. , 6. ])

In [24]:
arr2.ndim

1

In [26]:
arr2.shape

(9,)

In [27]:
arr2.size

9

In [47]:
arr3 = np.array([
    [2,6,9],
    [9,2,5]
])
arr3.setflags(write=False)
arr3

array([[2, 6, 9],
       [9, 2, 5]])

In [49]:
arr3[0][0] = 3

ValueError: assignment destination is read-only

In [29]:
arr3.ndim

2

In [31]:
arr3.shape

(2, 3)

In [32]:
arr3.size

6

In [33]:
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 7. , 5. , 6. ])

In [34]:
arr2[6] = 5

In [35]:
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 5. , 5. , 6. ])

In [37]:
arr2[5]= 9

In [38]:
arr2

array([5., 8., 9., 6., 5., 9., 5., 5., 6.])

In [41]:
arr2.reshape((3,3))

array([[5., 8., 9.],
       [6., 5., 9.],
       [5., 5., 6.]])

In [42]:
arr3

array([[2, 6, 9],
       [9, 2, 5]])

In [43]:
arr3.flatten()

array([2, 6, 9, 9, 2, 5])

In [6]:
arr4 = np.array(
    [[1,2,6],
     [6,8,9],
     [6,9,8]]
               )
arr4

array([[1, 2, 6],
       [6, 8, 9],
       [6, 9, 8]])

In [7]:
arr4.ndim

2

In [8]:
arr4.shape

(3, 3)

In [9]:
arr5 = np.array(
    [[1,5,6],
     [9,8,5],
     [1,8,8]]
               )
arr5

array([[1, 5, 6],
       [9, 8, 5],
       [1, 8, 8]])

In [14]:
#arr5[paralles][row][coll]

In [15]:
arr5[1][2]

5

In [11]:
m1 = np.matrix(arr4)
m2 = np.matrix(arr5)
m2

matrix([[1, 5, 6],
        [9, 8, 5],
        [1, 8, 8]])

In [12]:
m1 * m2

matrix([[ 25,  69,  64],
        [ 87, 166, 148],
        [ 95, 166, 145]])

# Pandas

In [16]:
import pandas as pd

In [24]:
df = pd.read_csv("iris-data.csv")

In [25]:
df.head(10)

sepal-length  sepal-width  petal-length   petal-width        class
0           5.1          3.5           1.4           0.2  Iris-setosa
1           4.9          3.0           1.4           0.2  Iris-setosa
2           4.7          3.2           1.3           0.2  Iris-setosa
3           4.6          3.1           1.5           0.2  Iris-setosa
4           5.0          3.6           1.4           0.2  Iris-setosa
5           5.4          3.9           1.7           0.4  Iris-setosa
6           4.6          3.4           1.4           0.3  Iris-setosa
7           5.0          3.4           1.5           0.2  Iris-setosa
8           4.4          2.9           1.4           0.2  Iris-setosa
9           4.9          3.1           1.5           0.1  Iris-setosa

In [22]:
df.tail(10)

5.1  3.5  1.4  0.2     Iris-setosa
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [28]:
df.iloc[0]

sepal-length            5.1
sepal-width             3.5
petal-length            1.4
 petal-width            0.2
class           Iris-setosa
Name: 0, dtype: object

In [29]:
df.iloc[:7]

sepal-length  sepal-width  petal-length   petal-width        class
0           5.1          3.5           1.4           0.2  Iris-setosa
1           4.9          3.0           1.4           0.2  Iris-setosa
2           4.7          3.2           1.3           0.2  Iris-setosa
3           4.6          3.1           1.5           0.2  Iris-setosa
4           5.0          3.6           1.4           0.2  Iris-setosa
5           5.4          3.9           1.7           0.4  Iris-setosa
6           4.6          3.4           1.4           0.3  Iris-setosa

In [30]:
df.describe()

sepal-length  sepal-width  petal-length   petal-width
count    150.000000   150.000000    150.000000    150.000000
mean       5.843333     3.054000      3.758667      1.198667
std        0.828066     0.433594      1.764420      0.763161
min        4.300000     2.000000      1.000000      0.100000
25%        5.100000     2.800000      1.600000      0.300000
50%        5.800000     3.000000      4.350000      1.300000
75%        6.400000     3.300000      5.100000      1.800000
max        7.900000     4.400000      6.900000      2.500000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3    petal-width  150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [32]:
df.describe(include='object')

class
count           150
unique            3
top     Iris-setosa
freq             50

In [33]:
df['sepal-length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal-length, Length: 150, dtype: float64

In [34]:
df.iloc[0]

sepal-length            5.1
sepal-width             3.5
petal-length            1.4
 petal-width            0.2
class           Iris-setosa
Name: 0, dtype: object

In [36]:
df[ ['sepal-length', 'petal-length' ] ].iloc[:10]

sepal-length  petal-length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4
5           5.4           1.7
6           4.6           1.4
7           5.0           1.5
8           4.4           1.4
9           4.9           1.5

In [38]:
df.columns

Index(['sepal-length', 'sepal-width', 'petal-length', ' petal-width', 'class'], dtype='object')