# Basic arrays

In [1]:
import array as arr

In [14]:
arr1 = arr.array('i',
    [25,6,9,5,8]
)

In [2]:
import numpy as np

In [21]:
arr2 = np.array([5,8,9,6,5,4.8,7,5,6])
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 7. , 5. , 6. ])

In [24]:
arr2.ndim

1

In [26]:
arr2.shape

(9,)

In [27]:
arr2.size

9

In [47]:
arr3 = np.array([
    [2,6,9],
    [9,2,5]
])
arr3.setflags(write=False)
arr3

array([[2, 6, 9],
       [9, 2, 5]])

In [49]:
arr3[0][0] = 3

ValueError: assignment destination is read-only

In [29]:
arr3.ndim

2

In [31]:
arr3.shape

(2, 3)

In [32]:
arr3.size

6

In [33]:
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 7. , 5. , 6. ])

In [34]:
arr2[6] = 5

In [35]:
arr2

array([5. , 8. , 9. , 6. , 5. , 4.8, 5. , 5. , 6. ])

In [37]:
arr2[5]= 9

In [38]:
arr2

array([5., 8., 9., 6., 5., 9., 5., 5., 6.])

In [41]:
arr2.reshape((3,3))

array([[5., 8., 9.],
       [6., 5., 9.],
       [5., 5., 6.]])

In [42]:
arr3

array([[2, 6, 9],
       [9, 2, 5]])

In [43]:
arr3.flatten()

array([2, 6, 9, 9, 2, 5])

In [6]:
arr4 = np.array(
    [[1,2,6],
     [6,8,9],
     [6,9,8]]
               )
arr4

array([[1, 2, 6],
       [6, 8, 9],
       [6, 9, 8]])

In [7]:
arr4.ndim

2

In [8]:
arr4.shape

(3, 3)

In [9]:
arr5 = np.array(
    [[1,5,6],
     [9,8,5],
     [1,8,8]]
               )
arr5

array([[1, 5, 6],
       [9, 8, 5],
       [1, 8, 8]])

In [14]:
#arr5[paralles][row][coll]

In [15]:
arr5[1][2]

5

In [11]:
m1 = np.matrix(arr4)
m2 = np.matrix(arr5)
m2

matrix([[1, 5, 6],
        [9, 8, 5],
        [1, 8, 8]])

In [12]:
m1 * m2

matrix([[ 25,  69,  64],
        [ 87, 166, 148],
        [ 95, 166, 145]])

# Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("iris-data.csv")

In [4]:
df.head(10)

sepal-length  sepal-width  petal-length   petal-width        class
0           5.1          3.5           1.4           0.2  Iris-setosa
1           4.9          3.0           1.4           0.2  Iris-setosa
2           4.7          3.2           1.3           0.2  Iris-setosa
3           4.6          3.1           1.5           0.2  Iris-setosa
4           5.0          3.6           1.4           0.2  Iris-setosa
5           5.4          3.9           1.7           0.4  Iris-setosa
6           4.6          3.4           1.4           0.3  Iris-setosa
7           5.0          3.4           1.5           0.2  Iris-setosa
8           4.4          2.9           1.4           0.2  Iris-setosa
9           4.9          3.1           1.5           0.1  Iris-setosa

In [5]:
df.tail(10)

sepal-length  sepal-width  petal-length   petal-width           class
140           6.7          3.1           5.6           2.4  Iris-virginica
141           6.9          3.1           5.1           2.3  Iris-virginica
142           5.8          2.7           5.1           1.9  Iris-virginica
143           6.8          3.2           5.9           2.3  Iris-virginica
144           6.7          3.3           5.7           2.5  Iris-virginica
145           6.7          3.0           5.2           2.3  Iris-virginica
146           6.3          2.5           5.0           1.9  Iris-virginica
147           6.5          3.0           5.2           2.0  Iris-virginica
148           6.2          3.4           5.4           2.3  Iris-virginica
149           5.9          3.0           5.1           1.8  Iris-virginica

In [6]:
df.iloc[0]

sepal-length            5.1
sepal-width             3.5
petal-length            1.4
 petal-width            0.2
class           Iris-setosa
Name: 0, dtype: object

In [7]:
df.iloc[:7]

sepal-length  sepal-width  petal-length   petal-width        class
0           5.1          3.5           1.4           0.2  Iris-setosa
1           4.9          3.0           1.4           0.2  Iris-setosa
2           4.7          3.2           1.3           0.2  Iris-setosa
3           4.6          3.1           1.5           0.2  Iris-setosa
4           5.0          3.6           1.4           0.2  Iris-setosa
5           5.4          3.9           1.7           0.4  Iris-setosa
6           4.6          3.4           1.4           0.3  Iris-setosa

In [8]:
df.describe()

sepal-length  sepal-width  petal-length   petal-width
count    150.000000   150.000000    150.000000    150.000000
mean       5.843333     3.054000      3.758667      1.198667
std        0.828066     0.433594      1.764420      0.763161
min        4.300000     2.000000      1.000000      0.100000
25%        5.100000     2.800000      1.600000      0.300000
50%        5.800000     3.000000      4.350000      1.300000
75%        6.400000     3.300000      5.100000      1.800000
max        7.900000     4.400000      6.900000      2.500000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3    petal-width  150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
df.describe(include='object')

class
count           150
unique            3
top     Iris-setosa
freq             50

In [11]:
df['sepal-length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal-length, Length: 150, dtype: float64

In [12]:
df.iloc[0]

sepal-length            5.1
sepal-width             3.5
petal-length            1.4
 petal-width            0.2
class           Iris-setosa
Name: 0, dtype: object

In [13]:
df[ ['sepal-length', 'petal-length' ] ].iloc[:10]

sepal-length  petal-length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4
5           5.4           1.7
6           4.6           1.4
7           5.0           1.5
8           4.4           1.4
9           4.9           1.5

In [14]:
df.columns

Index(['sepal-length', 'sepal-width', 'petal-length', ' petal-width', 'class'], dtype='object')

In [26]:
df[ [df['sepal-length']==6.4&df['petal-length']>5] ]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

# Descriptive Stats

1. Numerical data
    a. Descrete  
    b. continuous 
2. catagorical data
3. Ordinal data

mean -> averge of dataset
median -> middle val after sorting
mode -> more frequest val
SD -> userd to find the unusual datapoints
variance - > more the var more the data is spread out in the dataset


In [27]:
df.mean()

C:\Users\lokanath\AppData\Local\Temp\ipykernel_3092\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


sepal-length    5.843333
sepal-width     3.054000
petal-length    3.758667
 petal-width    1.198667
dtype: float64

In [28]:
df.median()

C:\Users\lokanath\AppData\Local\Temp\ipykernel_3092\530051474.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()


sepal-length    5.80
sepal-width     3.00
petal-length    4.35
 petal-width    1.30
dtype: float64

In [32]:
df.mode(numeric_only=True)

sepal-length  sepal-width  petal-length   petal-width
0           5.0          3.0           1.5           0.2

In [33]:
df.var()

C:\Users\lokanath\AppData\Local\Temp\ipykernel_3092\1568254755.py:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.var()


sepal-length    0.685694
sepal-width     0.188004
petal-length    3.113179
 petal-width    0.582414
dtype: float64

In [34]:
df.std()

C:\Users\lokanath\AppData\Local\Temp\ipykernel_3092\3390915376.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()


sepal-length    0.828066
sepal-width     0.433594
petal-length    1.764420
 petal-width    0.763161
dtype: float64

In [35]:
df[df['petal-length']>(1.764420*3.758667)]

sepal-length  sepal-width  petal-length   petal-width           class
117           7.7          3.8           6.7           2.2  Iris-virginica
118           7.7          2.6           6.9           2.3  Iris-virginica
122           7.7          2.8           6.7           2.0  Iris-virginica

In [36]:
df.corr()

C:\Users\lokanath\AppData\Local\Temp\ipykernel_3092\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


sepal-length  sepal-width  petal-length   petal-width
sepal-length      1.000000    -0.109369      0.871754      0.817954
sepal-width      -0.109369     1.000000     -0.420516     -0.356544
petal-length      0.871754    -0.420516      1.000000      0.962757
 petal-width      0.817954    -0.356544      0.962757      1.000000

In [37]:
wine_df = pd.read_csv('wine.csv')

In [38]:
wine_df.head()

INDEX  TARGET  FixedAcidity  VolatileAcidity  CitricAcid  ResidualSugar  \
0      1       3           3.2            1.160       -0.98           54.2   
1      2       3           4.5            0.160       -0.81           26.1   
2      4       5           7.1            2.640       -0.88           14.8   
3      5       3           5.7            0.385        0.04           18.8   
4      6       4           8.0            0.330       -1.26            9.4   

   Chlorides  FreeSulfurDioxide  TotalSulfurDioxide  Density    pH  Sulphates  \
0     -0.567                NaN               268.0  0.99280  3.33      -0.59   
1     -0.425               15.0              -327.0  1.02792  3.38       0.70   
2      0.037              214.0               142.0  0.99518  3.12       0.48   
3     -0.425               22.0               115.0  0.99640  2.24       1.83   
4        NaN             -167.0               108.0  0.99457  3.12       1.77   

   Alcohol  LabelAppeal  AcidIndex  STARS  
0      9.9            0          8    2.0  
1      NaN           -1          7    3.0  
2     22.0           -1          8    3.0  
3      6.2           -1          6    1.0  
4     13.7            0          9    2.0

In [39]:
wine_df.describe()

INDEX        TARGET  FixedAcidity  VolatileAcidity  \
count  12795.000000  12795.000000  12795.000000     12795.000000   
mean    8069.980305      3.029074      7.075717         0.324104   
std     4656.905107      1.926368      6.317643         0.784014   
min        1.000000      0.000000    -18.100000        -2.790000   
25%     4037.500000      2.000000      5.200000         0.130000   
50%     8110.000000      3.000000      6.900000         0.280000   
75%    12106.500000      4.000000      9.500000         0.640000   
max    16129.000000      8.000000     34.400000         3.680000   

         CitricAcid  ResidualSugar     Chlorides  FreeSulfurDioxide  \
count  12795.000000   12179.000000  12157.000000       12148.000000   
mean       0.308413       5.418733      0.054822          30.845571   
std        0.862080      33.749379      0.318467         148.714558   
min       -3.240000    -127.800000     -1.171000        -555.000000   
25%        0.030000      -2.000000     -0.031000           0.000000   
50%        0.310000       3.900000      0.046000          30.000000   
75%        0.580000      15.900000      0.153000          70.000000   
max        3.860000     141.150000      1.351000         623.000000   

       TotalSulfurDioxide       Density            pH     Sulphates  \
count        12113.000000  12795.000000  12400.000000  11585.000000   
mean           120.714233      0.994203      3.207628      0.527112   
std            231.913211      0.026538      0.679687      0.932129   
min           -823.000000      0.888090      0.480000     -3.130000   
25%             27.000000      0.987720      2.960000      0.280000   
50%            123.000000      0.994490      3.200000      0.500000   
75%            208.000000      1.000515      3.470000      0.860000   
max           1057.000000      1.099240      6.130000      4.240000   

            Alcohol   LabelAppeal     AcidIndex        STARS  
count  12142.000000  12795.000000  12795.000000  9436.000000  
mean      10.489236     -0.009066      7.772724     2.041755  
std        3.727819      0.891089      1.323926     0.902540  
min       -4.700000     -2.000000      4.000000     1.000000  
25%        9.000000     -1.000000      7.000000     1.000000  
50%       10.400000      0.000000      8.000000     2.000000  
75%       12.400000      1.000000      8.000000     3.000000  
max       26.500000      2.000000     17.000000     4.000000

In [40]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12795 entries, 0 to 12794
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   INDEX               12795 non-null  int64  
 1   TARGET              12795 non-null  int64  
 2   FixedAcidity        12795 non-null  float64
 3   VolatileAcidity     12795 non-null  float64
 4   CitricAcid          12795 non-null  float64
 5   ResidualSugar       12179 non-null  float64
 6   Chlorides           12157 non-null  float64
 7   FreeSulfurDioxide   12148 non-null  float64
 8   TotalSulfurDioxide  12113 non-null  float64
 9   Density             12795 non-null  float64
 10  pH                  12400 non-null  float64
 11  Sulphates           11585 non-null  float64
 12  Alcohol             12142 non-null  float64
 13  LabelAppeal         12795 non-null  int64  
 14  AcidIndex           12795 non-null  int64  
 15  STARS               9436 non-null   float64
dtypes: f

In [41]:
wine_df.columns

Index(['INDEX', 'TARGET', 'FixedAcidity', 'VolatileAcidity', 'CitricAcid',
       'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide',
       'Density', 'pH', 'Sulphates', 'Alcohol', 'LabelAppeal', 'AcidIndex',
       'STARS'],
      dtype='object')

In [42]:
wine_df.mean()

INDEX                 8069.980305
TARGET                   3.029074
FixedAcidity             7.075717
VolatileAcidity          0.324104
CitricAcid               0.308413
ResidualSugar            5.418733
Chlorides                0.054822
FreeSulfurDioxide       30.845571
TotalSulfurDioxide     120.714233
Density                  0.994203
pH                       3.207628
Sulphates                0.527112
Alcohol                 10.489236
LabelAppeal             -0.009066
AcidIndex                7.772724
STARS                    2.041755
dtype: float64

In [43]:
wine_df.median()

INDEX                 8110.00000
TARGET                   3.00000
FixedAcidity             6.90000
VolatileAcidity          0.28000
CitricAcid               0.31000
ResidualSugar            3.90000
Chlorides                0.04600
FreeSulfurDioxide       30.00000
TotalSulfurDioxide     123.00000
Density                  0.99449
pH                       3.20000
Sulphates                0.50000
Alcohol                 10.40000
LabelAppeal              0.00000
AcidIndex                8.00000
STARS                    2.00000
dtype: float64

In [49]:
df2 = wine_df[['FixedAcidity', 'VolatileAcidity', 'CitricAcid',
       'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide',
       'Density', 'pH', 'Sulphates', 'Alcohol', 'LabelAppeal', 'AcidIndex']]

In [51]:
df2.mode()

FixedAcidity  VolatileAcidity  CitricAcid  ResidualSugar  Chlorides  \
0           6.8             0.24         0.3            1.4      0.036   
1           NaN              NaN         NaN            NaN      0.044   

   FreeSulfurDioxide  TotalSulfurDioxide  Density    pH  Sulphates  Alcohol  \
0               29.0               125.0   0.9976  3.22        0.5      9.4   
1                NaN                 NaN      NaN   NaN        NaN      NaN   

   LabelAppeal  AcidIndex  
0          0.0        7.0  
1          NaN        NaN

In [52]:
df2.var()

FixedAcidity             39.912619
VolatileAcidity           0.614678
CitricAcid                0.743182
ResidualSugar          1139.020582
Chlorides                 0.101421
FreeSulfurDioxide     22116.019658
TotalSulfurDioxide    53783.737208
Density                   0.000704
pH                        0.461975
Sulphates                 0.868865
Alcohol                  13.896635
LabelAppeal               0.794040
AcidIndex                 1.752781
dtype: float64

In [53]:
df2['FreeSulfurDioxide']

0          NaN
1         15.0
2        214.0
3         22.0
4       -167.0
         ...  
12790     17.0
12791     54.0
12792     25.0
12793     26.0
12794   -106.0
Name: FreeSulfurDioxide, Length: 12795, dtype: float64

In [54]:
df2.std()

FixedAcidity            6.317643
VolatileAcidity         0.784014
CitricAcid              0.862080
ResidualSugar          33.749379
Chlorides               0.318467
FreeSulfurDioxide     148.714558
TotalSulfurDioxide    231.913211
Density                 0.026538
pH                      0.679687
Sulphates               0.932129
Alcohol                 3.727819
LabelAppeal             0.891089
AcidIndex               1.323926
dtype: float64

In [55]:
df2.corr()

FixedAcidity  VolatileAcidity  CitricAcid  ResidualSugar  \
FixedAcidity            1.000000         0.012375    0.014240      -0.018855   
VolatileAcidity         0.012375         1.000000   -0.016953      -0.006483   
CitricAcid              0.014240        -0.016953    1.000000      -0.006940   
ResidualSugar          -0.018855        -0.006483   -0.006940       1.000000   
Chlorides              -0.000457         0.000987   -0.008567      -0.005594   
FreeSulfurDioxide       0.004972        -0.007077    0.006428       0.017493   
TotalSulfurDioxide     -0.022498        -0.021080    0.006320       0.022479   
Density                 0.006477         0.014735   -0.013952       0.004101   
pH                     -0.008983         0.013592   -0.008709       0.012118   
Sulphates               0.030783         0.000129   -0.012989      -0.007723   
Alcohol                -0.009371         0.004073    0.017046      -0.019998   
LabelAppeal            -0.003366        -0.016987    0.008650       0.002320   
AcidIndex               0.178437         0.044642    0.065697      -0.009414   

                    Chlorides  FreeSulfurDioxide  TotalSulfurDioxide  \
FixedAcidity        -0.000457           0.004972           -0.022498   
VolatileAcidity      0.000987          -0.007077           -0.021080   
CitricAcid          -0.008567           0.006428            0.006320   
ResidualSugar       -0.005594           0.017493            0.022479   
Chlorides            1.000000          -0.020661           -0.013994   
FreeSulfurDioxide   -0.020661           1.000000            0.013720   
TotalSulfurDioxide  -0.013994           0.013720            1.000000   
Density              0.022657           0.003176            0.012816   
pH                  -0.017605           0.006049           -0.004343   
Sulphates           -0.003290           0.011593           -0.007133   
Alcohol             -0.019695          -0.018588           -0.015957   
LabelAppeal          0.010509           0.010294           -0.009747   
AcidIndex            0.025238          -0.041717           -0.049311   

                     Density        pH  Sulphates   Alcohol  LabelAppeal  \
FixedAcidity        0.006477 -0.008983   0.030783 -0.009371    -0.003366   
VolatileAcidity     0.014735  0.013592   0.000129  0.004073    -0.016987   
CitricAcid         -0.013952 -0.008709  -0.012989  0.017046     0.008650   
ResidualSugar       0.004101  0.012118  -0.007723 -0.019998     0.002320   
Chlorides           0.022657 -0.017605  -0.003290 -0.019695     0.010509   
FreeSulfurDioxide   0.003176  0.006049   0.011593 -0.018588     0.010294   
TotalSulfurDioxide  0.012816 -0.004343  -0.007133 -0.015957    -0.009747   
Density             1.000000  0.005768  -0.009059 -0.007215    -0.009370   
pH                  0.005768  1.000000   0.005475 -0.011548     0.004138   
Sulphates          -0.009059  0.005475   1.000000  0.004741    -0.003888   
Alcohol            -0.007215 -0.011548   0.004741  1.000000     0.001027   
LabelAppeal        -0.009370  0.004138  -0.003888  0.001027     1.000000   
AcidIndex           0.040413 -0.058676   0.034449 -0.038138     0.024755   

                    AcidIndex  
FixedAcidity         0.178437  
VolatileAcidity      0.044642  
CitricAcid           0.065697  
ResidualSugar       -0.009414  
Chlorides            0.025238  
FreeSulfurDioxide   -0.041717  
TotalSulfurDioxide  -0.049311  
Density              0.040413  
pH                  -0.058676  
Sulphates            0.034449  
Alcohol             -0.038138  
LabelAppeal          0.024755  
AcidIndex            1.000000